# Основная конфигурация плагина RProfile
profile:
  enabled: true  # Включить или отключить команду /profile
  message: "Команда отключена."  # Сообщение при отключенной команде

lang:
  profile: "У вас нет прав на выполнение этой команды."  # Сообщение при отсутствии прав на команду /profile

# Сообщения для команды /language
language:
  usage: "Использование: /language <язык>"  # Использование команды /language
  invalid: "Неверно указан язык. Доступные варианты: Русский, English, Українська."  # Сообщение для неверного языка
  changed: "Язык изменен на: %language%"  # Сообщение при успешной смене языка
  error: "Произошла ошибка при изменении языка."  # Сообщение при ошибке изменения языка

# Сообщения для команды /gender
gender:
  usage: "Использование: /gender <пол>"  # Использование команды /gender
  invalid: "Неверно указан пол. Доступные варианты: Мужской, Женский."  # Сообщение для неверного пола
  changed: "Пол изменен на: %gender%"  # Сообщение при успешной смене пола
  error: "Произошла ошибка при изменении пола."  # Сообщение при ошибке изменения пола
