# config.yml - RProfile
#
# Support for HEX colors seems to be implemented.
# I suggest https://www.birdflop.com/resources/rgb/
# Example of coloring in this format: §x§3§8§3§8§C§C, it will definitely work.
#
profile:
  enabled: true  # Enable or disable the /profile command
  message: "The command is disabled in the config."  # Message when the command is disabled

lang:
  profile: "You do not have permission to execute this command."  # Message when lacking permission to use /profile

# Messages for the /language command
language:
  usage: "Usage: /language <language>"  # Usage instruction for the /language command
  invalid: "Invalid language specified. Available options: Русский, English, Українська."  # Message for invalid language input
  changed: "Language changed to: %language%"  # Message upon successful language change
  error: "An error occurred while changing the language."  # Message when there is an error changing the language

# Messages for the /gender command
gender:
  usage: "Usage: /gender <gender>"  # Usage instruction for the /gender command
  invalid: "Invalid gender specified. Available options: Male, Female."  # Message for invalid gender input
  changed: "Gender changed to: %gender%"  # Message upon successful gender change
  error: "An error occurred while changing the gender."  # Message when there is an error changing the gender
