name: rProfiles
version: '1.3'
main: org.plugin.rProfile.RProfile
api-version: '1.20'
authors: [ reallmerry ]
description: Команда /profile. Используемая на проекте Craftopia (2025)
website: https://t.me/uselessnesc
softdepend: [LuckPerms]

commands:
  profile:
    description: seen profile player
    aliases:
      - profil
      - passport
      - account
      -
  language:
    description: set language
  gender:
    description: set gender

  rprofile:
    description: command
    aliases:
      - rp
      - ra
      - prof
      - main

  callreload:
    description: test command
